### ISSUE TITLE
Emptying fish barrel at the bank is no longer tracked

### ISSUE THREAD

**Issue by RhysThompson** [MosheBenZacharia/GP-Per-Hour#73]
If the fish barrel is emptied at the bank then when you leave the bank if you check the barrel it will say that you have lost the previous contents.

The option for emptying to the bank is now "Empty to bank" rather than "Empty", I would assume that's why it no longer works.

**Comment by MosheBenZacharia** [comment]
sorry this took forever, I forgot about it. should be fixed when this merges:

https://github.com/runelite/plugin-hub/pull/10562

**Comment by RerEirikr** [comment]
> sorry this took forever, I forgot about it. should be fixed when this merges:
> 
> [runelite/plugin-hub#10562](https://github.com/runelite/plugin-hub/pull/10562)

Looking forward to the fix/update. Thank you very much! Will report back.

**Comment by RerEirikr** [comment]
It does still seem to not be tracking properly when fishing and banking. I'm still seeing the plugin ignore crabs that are within the barrel, and then if I check a barrel it starts implying I'm actually missing crabs until it is full, almost like it's trying to reach net zero with a full barrel.

**Comment by MosheBenZacharia** [comment]
is this only at dark crabs?

**Comment by RerEirikr** [comment]
I'll see if I can replicate it elsewhere. Once I start a new trip, check the barrel, let's say we're at -28 crabs now, I start *another* new trip, delete that old one, and check again, and we're starting from neutral with tracking as expected, if that helps.

**Comment by RerEirikr** [comment]
Able to replicate the issue with Karambwans as well. Attaching an image for assistance in explaining.

How to replicate:
1) Fish Karambwan, for the sake of testing I did it until I had more than enough to fill up the fish barrel and a fair amount of inventory.
2) Empty barrel and inventory into bank, notably using the **Empty** function on the barrel, not the empty containers button
3) New trip is started
4) Check Barrel
5) Trip immediately updates to -28 Karambwan

<img width="210" height="325" alt="Image" src="https://github.com/user-attachments/assets/6f385b04-6d83-42c8-a0d5-9444bee5dafd" />

I'll try this again using the empty containers button and see if that makes a difference.

**Comment by RerEirikr** [comment]
Using the Empty Containers button seems to have worked as intended, will perform additional tests to validate.

**Comment by RerEirikr** [comment]
Replicated again by using the **Empty** option on the Barrel itself while banking. 
Performed another example using the "Empty Containers" button, with a healthy outcome and plugin working as intended. 

Issue potentially seems tied to the Empty button on containers themselves.
